modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="minecraft_ultimate_forge"
version="1.0.0.100.1"
displayName="Minecraft Ultimate Forge"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="samuel vrignaud"
description="build 100.1"

[[dependencies.minecraft_ultimate_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




